[package]
name = "unf"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"
description = """
UNixize Filename -- replace annoying anti-unix characters in filenames
"""
readme = "README.md"
license = "MIT"

[dependencies]
clap = "2.33.0"
lazy_static = "1.3.0"
regex = "1.1.6"
failure = "0.1.5"
promptly = "0.1.5"
